## DO NOT RUN THE BLOCK BELOW

In [1]:

import pandas as pd
from sklearn.utils import shuffle
df=pd.read_csv("002_duplicate.csv")
#print(df['text'].iloc[5])
#print(df['text'].iloc[77])
df=shuffle(df)
print(df)
df.to_csv(path_or_buf="shuffled_tweets.csv")

               id  index                                               text
429  1.120000e+18    429  RT @HSELive: 300 women develop cervical cancer...
235  1.120000e+18    235  RT @SNCCLA: Court ruling highlights the threat...
442  1.120000e+18    442  RT @ViraBurnayeva: According to data compiled ...
272  1.120000e+18    272  RT @GaviSeth: Today is the anniversary of the ...
3    1.120000e+18      3  @BrianRAlexander Jonas Salk could’ve gotten in...
447  1.120000e+18    447                   @Finnpal https://t.co/3Z2EJ7cdEm
85   1.120000e+18     85  @FlexAddict Wait. What facts are you using? Th...
267  1.120000e+18    267  RT @behealthyusa: 13-Year-Boy Is Paralyzed Fro...
221  1.120000e+18    221  Full Interview - https://t.co/1zYfvxFWE3  How ...
333  1.120000e+18    333  @MichelleRempel Using it to relate to vaccines...
187  1.120000e+18    187  RT @nicd_sa: The Flu vaccine is necessary ever...
411  1.120000e+18    411  RT @drnikkistamp: Our heart transplant patient...
48   1.12000

In [9]:
df=pd.read_csv("shuffled_tweets.csv")

print(df)

               id  index                                               text  \
0    1.120000e+18      4  RT @SwedeninMZ: Cholera is a water-borne disea...   
1    1.120000e+18     82  3. Get Vaccinated : Vaccines are very good for...   
2    1.120000e+18     73  Measles: no vaccine, come another time. The in...   
3    1.120000e+18    306  RT @GaviSeth: Today is the anniversary of the ...   
4    1.120000e+18    437                            https://t.co/3Z2EJ7cdEm   
5    1.120000e+18    484  @picardonhealth I’ve receive Toronto Public He...   
6    1.120000e+18    201  @tammyhealy21 @kidoctr @ChrisJohnsonMD @Arcane...   
7    1.120000e+18     98  Opting out of measles vaccine could be a death...   
8    1.120000e+18    330  RT @ForeignPolicy: A recent study found that t...   
9    1.120000e+18    312  RT @BellHappe: @DoctorChristian https://t.co/q...   
10   1.120000e+18    300  RT @slealey53: I'm just posting this to make y...   
11   1.120000e+18    347  @duxmom24 @daveleifer Argu

## DO NOT RUN THE BLOCK BELOW

In [23]:
df=pd.read_csv("All_HITS.csv")
#print(df)
shuffled_df=shuffle(df)
print(shuffled_df)
shuffled_df.to_csv("shuffled_all_HITS.csv")

               id  index                                               text  \
309  1.120000e+18    309  RT @ForeignPolicy: A recent study found that t...   
178  1.120000e+18    178  RT @ForeignPolicy: A recent study found that t...   
357  1.120000e+18    357  RT @Stephenteap: My wife was one of the 90 wom...   
409  1.120000e+18    409  RT @nicd_sa: The Flu vaccine is necessary ever...   
112  1.120000e+18    112  RT @nltarlow: You want to force #vaccinations,...   
403  1.120000e+18    403  @DavidTaormia @TheSolariReport @OWingsgirl The...   
247  1.120000e+18    247  @OhioAMF I am in Virginia. What can I do to he...   
144  1.120000e+18    144  RT @dpmlawfirm: Drug Company Dollars control V...   
265  1.120000e+18    265  RT @IreneGentle: 'Nearly 10 million tweets fro...   
378  1.120000e+18    378  RT @Wallace_Noll: @DoctorChristian Dr. Nicole ...   
390  1.120000e+18    390  RT @hillemanlabs: A vaccine contains antigens ...   
374  1.120000e+18    374  RT @Wallace_Noll: @DoctorC

In [26]:
batch=pd.read_csv("Batch_results.csv")
print(batch)



                              HITId                       HITTypeId  \
0    3D06DR52257XEDID1VJ1IX19Q62AMC  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
1    3DA79LNS59J17N9C1D53H3IVE463TA  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
2    3QREJ3J433LJK89EDAVBCYPGVD6LK0  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
3    3SX4X51T80XLEG3PEBYEA1QEL6HAOR  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
4    39HYCOOPKO9VCKLPL5A38Y9FB9ZDMH  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
5    37SDSEDIN9QMZ039BBGP2E7B27781Y  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
6    3K3IX1W4S6F3ZGFQTBBTZ1V4VBDAP8  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
7    3VMHWJRYHV434GYPQI727FSYUQZFXE  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
8    3JMQI2OLFZT1U26PX6P3LDYFGZ9DNH  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
9    3TC2K6WK9GQTOLL5UFG37XHGUDL82F  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
10   3YZ7A3YHR5H362J1QWO6MVKTQHJ5SD  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
11   3J5XXLQDHMZGKFD1685IIL6GBPM3VQ  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
12   3D42WVSDH8JS4LOZVET4QTZ7WWTFYK  3WIABKGAUQPI5FMGOCKM90N4CXV6EO   
13   3

In [36]:
import numpy as np
average_time=batch['WorkTimeInSeconds'].mean()
print(average_time)

print(batch['Input.Annotation'].isnull().values)
"""for i in range(114):
    print(batch.iloc[i,30])"""
print(batch.iloc[2,30]==batch.iloc[2,31])

8.68421052631579
[ True  True False  True  True  True  True  True  True False  True  True
  True  True  True  True False False  True  True  True False  True  True
  True  True  True  True  True  True  True False  True  True  True  True
  True  True  True False  True False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False  True
  True False  True False  True  True  True False  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True False  True  True  True False  True  True
 False False False  True  True  True  True  True  True  True  True False
  True  True  True  True  True  True]
False


In [2]:
real_batch=pd.read_csv("Real_Batch.csv")
print(real_batch.shape)
worker_id=real_batch['WorkerId'].unique()
print(worker_id)
print(len(worker_id))

(1805, 31)
['A1GZZGA7ZFUPMB' 'A3W0C04EXOY12C' 'A2KDT0S0L81JGF' 'ARIBVG7WV64QM'
 'A3NOXFQNEWTIDF' 'A2ITJNPW1LDUN7' 'A3UNJAPZMVOFM2' 'AGNJKSH5LFKXZ'
 'A3AGJSGD009WMM' 'A3D4BKBC0RRBYQ' 'A1Q7KDP8IYSSUT' 'AI3RROIIG6ZXW'
 'A1NB72ONBBX1UQ' 'A38IGWR6VEHCNE' 'AO4T2UHNL59A8' 'A14GWDUSY7R4NP'
 'A2KELVTQL5F8VB' 'AF2FQOM5UUWT2' 'A1WGEJVGY3DI13' 'A14EEWC3KEF63G'
 'A2Z2JYY5050FNL' 'A124C2FN9KS2SW' 'A34AQDMF5GVHVY' 'A38R689MVZST8Q'
 'A1TQ9QP0VWGTXU' 'A3LRE22F3AHPQ2' 'A15YYU3A3SW1T9' 'A1PV2ML7YCJM4K'
 'A1MR9YZ7D7E34G' 'AUZ6D57S6ZENL' 'A1FG2G9TZSDN' 'A1N1ULK71RHVMM'
 'A2R0Y8A3SSZ30S' 'A3HL3Q7QCBYZ2Y' 'A2JBYGXAZAYBWY' 'A1FYGRDLIK4312'
 'A20NITCOBY4775' 'ARI3DSMOGMJJA' 'A3K2ZXAFZCHYZI' 'A1GUGCOS9HM63C'
 'A3DS9DP2JE8I4Z' 'AO8B5M4K8WDA7' 'A2BBQ4K7FB2B5Z' 'A28U1GCCY9R6O4'
 'AENJ7GDYBENYX' 'A2RR2BUAT4C3T7' 'ARQ7A1D0HXFRA' 'A3U6CLX7HD0SMF'
 'A1RXNKDRFO7B0X' 'A2KJ983WWTEK4L' 'A14294HZGND1AZ' 'A349IESC62JQF9'
 'A35506802CMX5T' 'A2J92I8PSCDFCC' 'A1160COTUR26JZ' 'A1H8Y5D04A7T5E'
 'A2LKL8MNCVTPXD' 'A1Q8PPQQCWGY0D' 

In [3]:
#extract the tweet and final annotation for model training and testing
cols=['tweet','Final_Annotation']
training_df=real_batch[cols]
df=training_df.dropna()
print(df)

                                                 tweet Final_Annotation
0    #Meningitis: a group A polysaccharide tetanus ...     anti-vaccine
1    Our PhD student, Madeleine Clark, is out in th...     anti-vaccine
2    @BrianRAlexander Jonas Salk could’ve gotten ...      pro-vaccine
3    RT @SwedeninMZ: Cholera is a water-borne disea...          neither
4    RT @MichelleRempel: Get vaccinated, and vaccin...      pro-vaccine
5    RT @ForeignPolicy: A recent study found that t...      pro-vaccine
6    RT @SJVanders: My article on #pro-vaccine acti...      pro-vaccine
7    RT @ForeignPolicy: A recent study found that t...      pro-vaccine
8    RT @Boxmenot: @chickenlady100 @MeddlinMegs @Kr...          neither
9    15 charts explain the vaccine problem in the U...      pro-vaccine
10   RT @BeckyJohnson222: @kidoctr @rugbyrhino16 @m...          neither
11   Are you following a #Vaccine schedule? Here's ...      pro-vaccine
12   @HLN_BE @Maggie_DeBlock, de orde van geneesher...      pro-

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(df['tweet'])
X_train_counts.shape



(601, 3010)

In [5]:
X_train_counts.reshape(-1,1)
X_train_counts.shape

(601, 3010)

In [6]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(601, 3010)

In [78]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.model_selection import KFold
from sklearn import svm, metrics
seed=np.random.RandomState(0)
kf = KFold(n_splits=10, random_state=seed,shuffle=False)
scores=[]
for train_index, test_index in kf.split(X_train_tfidf):
    clf = MultinomialNB()
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X_train_tfidf[train_index], X_train_tfidf[test_index]
    y_train, y_test = df['Final_Annotation'][train_index], df['Final_Annotation'][test_index]
    clf.fit(X_train, y_train)
    annotation_pred = clf.predict(X_test)
     # The coefficients
    print('Coefficients : \n', clf.coef_)
    # The mean squared error
    # Explained variance score: 1 is perfect prediction
    print('Score is: %.2f' % clf.score(X_test,y_test))
    scores.append(clf.score(X_test,y_test))
    print()
    print("Classification report for classifier %s\n%s\n" % (clf, metrics.classification_report(y_test, annotation_pred)))
    # Print out the confusion matrix. PS: edible is 0, poisonous is 1
    print("Confusion Matrix:\n%s" % metrics.confusion_matrix(y_test, annotation_pred,labels=['anti-vaccine','pro-vaccine','neither']))
print("The scores for 10-folds cross validation are: ")
print(scores)
print("The average score for 10-folds cross validation is: "+ str(np.mean(scores)))



TRAIN: [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114
 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132
 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204
 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222
 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240
 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258
 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276
 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294
 295 296 297 298 299 300 301 302 303 304 305

Score is: 0.42

Classification report for classifier MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
              precision    recall  f1-score   support

anti-vaccine       0.40      0.17      0.24        23
     neither       0.25      0.10      0.14        10
 pro-vaccine       0.43      0.74      0.55        27

   micro avg       0.42      0.42      0.42        60
   macro avg       0.36      0.34      0.31        60
weighted avg       0.39      0.42      0.36        60


Confusion Matrix:
[[ 4 18  1]
 [ 5 20  2]
 [ 1  8  1]]
The scores for 10-folds cross validation are: 
[0.47540983606557374, 0.5, 0.5, 0.55, 0.48333333333333334, 0.55, 0.5833333333333334, 0.5, 0.55, 0.4166666666666667]
The average score for 10-folds cross validation is: 0.5108743169398908
